### ISSUE TITLE
--Portable option is not working

### ISSUE THREAD

**Issue by AlexandreFerreiraRJ** [sepinf-inc/IPED#103]
The --portable option continues to consider the absolute path of E01, when you run IPED.

Version 3.17.3

**Comment by tc-wleite** [comment]
@AlexandreFerreiraRJ, can you post an example of the exact command you are using?

**Comment by AlexandreFerreiraRJ** [comment]
IPED with --portable option :

![image](https://user-images.githubusercontent.com/4698779/82916675-57eb8e80-9f40-11ea-99a2-3b6b41d11978.png)

When you run IPED.

![image](https://user-images.githubusercontent.com/4698779/82917197-1c04f900-9f41-11ea-8136-d503f2fa6374.png)

**Comment by tc-wleite** [comment]
I meant the full exact command.

**Comment by lfcnassif** [comment]
This is a known problem, the image path is updated to be relative, but later is changed to absolute again at the end of processing, if I remember. It is not very bad, because GUI tries some heuristics to fix the image path if not found, but that changes sleuth.db content.

**Comment by tc-wleite** [comment]
Are you sure @lfcnassif? 
We always used the **--portable** option here and it keeps the relative path.

I just made a quick test, and it preserved the relative path as expected.
![image](https://user-images.githubusercontent.com/7217001/82951843-517c0780-9f7e-11ea-9938-138d4e2b8c60.png)

I asked @AlexandreFerreiraRJ the exact command because I think it could be some particular situation.

**Comment by lfcnassif** [comment]
Not sure :-) maybe I fixed what I described in the past...

@AlexandreFerreiraRJ, just a note, it will not work if your output folder is in a different drive letter than your input images.

**Comment by lfcnassif** [comment]
Closing, if the issue persists, please reopen and provide the info asked for.
