### ISSUE TITLE
Extract video frames as subitems to run all image processing modules on them

### ISSUE THREAD

**Issue by arisjr** [sepinf-inc/IPED#1081]
Dear developers,

I would like to request to the IPED project to use the same parsers and processing of the **image files** (like OCR, image similarity, and others)  on the **videos snapshots** (that are generated by IPED on videos). It will bring the ability to find more evidences on the video files. 

Best Regards,
Aristeu

**Comment by lfcnassif** [comment]
Hi @arisjr,

I agree image similarity could be run on the extracted video frames. But I'm not sure about OCR with our current approach, since the number of extracted frames and resolution are fixed and very low by default. Increasing them or making them dynamic could make the processing to take much longer, although increasing the frame count could benefit some cases, but increasing resolution would be a waste of resources if OCR is disabled.

Nudity detection is already run on extracted video frames. What **others** (features) you are thinking about?

**Comment by arisjr** [comment]
> although increasing the frame count could benefit some cases, but increasing resolution would be a waste of resources if OCR is disabled.

Maybe a flag like enableVideoFrameOCR, and maybe enableVideoFrameHighDefinition (it could be a command line option too - It would help on automated tasks), or something like that, that enables OCR on video files and increases the video frames definition?

> It is already implemented, just not released, and already run over video extracted frames, but many results could be missed given the current low resolution default configuration for frame extraction

Great news you're bringing! The enableVideoFrameHighDefinition flag would help in this case also. It could check the video definition and make the frame snapshot with the video original definition. I don't know if it's possible. It's just an idea.

**Comment by lfcnassif** [comment]
All of those ideas are possible, but we have very few human resources available... My current roadmap is this: https://github.com/sepinf-inc/IPED/projects/1

If you could help and draft some code and send a PR, I can review and test.
