### ISSUE TITLE
Out of memory when parsing contacts of whatsapp

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1248]
I was processing a huge case and an out of memory error occurred. After digging into the heap dump I think it is caused by this
`result = searcher.search(BasicProps.NAME + ":(" + escape(searcher, contact.getId()) + " AND (jpg thumb))");`

This query is returning a huge number of items, exhausting all the available memory.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh. I'll take a look at your heap dump today after lunch.

**Comment by lfcnassif** [comment]
Done. I agree with your analysis, that search resulted in ~2M items found and it is trying to instantiate all those Items (with all properties and thumbs), the OOM happened after ~1M was created.

I'm not sure, but I **think** this WAContact ID was used in that search:
554184323\ufffdy\ufffdw\ufffd{\u001c\u0000C\u0009\ufffd\u000f\u0005\u001f\u0002\u0019\u0001\u0000

I don't know why it resulted in that huge number of results, maybe the used ID in the query was another one...

Anyway, I'll put the escaped `contact.getId()` between double quotes like similar queries above in the code, and will change to use the `searcher.searchIterable(query)` method, it returns an Iterable instead of a List with all results and should protect against the OOM, although it may take a log time to iterate over all results.

@fmpfeifer, since I think you wrote this avatar search logic, please let me know if my proposed approach is ok or if you have a better idea to avoid getting that large number of results for avatars

**Comment by lfcnassif** [comment]
Another idea I had was to limit the number of returned results, but I'm not sure if it would break the input for `filterAvatars()` method called right below in the code.

**Comment by lfcnassif** [comment]
I just pushed a possible fix above, I'll test on the triggering case before merging.

**Comment by lfcnassif** [comment]
The processing of the huge triggering case finished, no aborting OOME thrown nor timeouts related to WhatsApp processing, so I'll merge the fix.
