### ISSUE TITLE
Invalid search input in Hex Viewer

### ISSUE THREAD

**Issue by hugohmk** [sepinf-inc/IPED#1277]
Currently, any string searched with Hex Viewer is being flagged as invalid. The problem seems to be related to the HVPComboField class, since changing jtfTextoHex into HVPTextField solved the issue (but the editor loses its ability to track previous searches).

**Comment by lfcnassif** [comment]
Does this happen with 3.18.x, 4.0.x or both?

**Comment by hugohmk** [comment]
It happens in 4.0.x, but I believe It does not in 3.18.x.

**Comment by lfcnassif** [comment]
I just reproduced with 4.0.2, it works with 3.18.15.

**Comment by lfcnassif** [comment]
Keyboard shortcuts also stopped to work.

**Comment by lfcnassif** [comment]
Hi @hugohmk, I pushed a fix. Please test this snapshot:
https://github.com/sepinf-inc/IPED/actions/runs/2871226223

You just need to replace the iped-viewers-4.x.jar in the lib folder of your case.

PS: I spent hours investigating this and I don't know why it stopped to work... Maybe java 11 event handling of JComboBox (or its internal JTextField) changed. So I had to change the event handling approach. Another thing, now the JComboBox is accepting any chars if 'Hexadecimal' search is selected, it used to accept just [0-9A-Fa-f]. I tried to make the filtering work again, but I didn't manage to. I don't think this is critical, because the UI warns about invalid hex chars when user hits 'enter'. If anyone know exactly how to make char filtering inside an editable JComboBox work again, please let me know.

**Comment by gfd2020** [comment]
I just saw this strange behavior today. It must be because of JDK 11. I'll take a look.

**Comment by gfd2020** [comment]
After a lot of tests, I finaly make it work. It works on JDK 11, but I have to set a new ComboBoxEditor. This is odd. I will commit the fix with orther fixes.

**Comment by lfcnassif** [comment]
Thank you @gfd2020 for taking a look into this too! If you could push the fix in another branch (different than filetypeicon) that would be great.

**Comment by gfd2020** [comment]
@lfcnassif , I fix this bug on hexviewerplus-jdk11-fix branch
