### ISSUE TITLE
Processing hanging in AudioTranscriptTask

### ISSUE THREAD

**Issue by hugohmk** [sepinf-inc/IPED#1292]
It seems that the timeout for AudioTranscriptTask is not working. Recently, I stumbled upon a file that caused the whole processing to halt during the AudioTranscriptTask. This was tested with versions 4.0.2 and 4.0.3.
The file was found inside an .obb from the "Toca Life World" android app.
[sharedassets20.assets.split2.zip](https://github.com/sepinf-inc/IPED/files/9446490/sharedassets20.assets.split2.zip)

**Comment by lfcnassif** [comment]
Hi @hugohmk,

Actually, the **Vosk** AudioTranscriptTask impl (are you using it?) module has no timeout control, I though it would never happen since it handles raw WAV data, maybe it happened while converting the audio format? Have you taken a thread dump showing the exact freezing point? I'll try to reproduce with the sample you provided.

**Comment by hugohmk** [comment]
Yes, i'm using it to process a case! I think you're right, there was a MPlayer.exe process that never finished processing - after terminating it manually, the case resumed normally.

**Comment by lfcnassif** [comment]
Ok thanks for confirming. So we will have to implement a timeout control, at least for the mplayer conversion part.

**Comment by lfcnassif** [comment]
Just reproduced, thanks for the triggering file! Pushing a simple fix shortly.

**Comment by lfcnassif** [comment]
Looking at the thread dump, it is blocked while reading the process input stream into a buffer, so I think this could also eventually trigger an OOME.

Strangely, trying to forcibly kill mplayer.exe on windows didn't work, mplayer.exe continues to loop indefinitely after IPED has finished. Calling process.getInputStream().close() blocks. Chaining process.destroy() then process.destroyForcibly() works (the first call actually). @tc-wleite I'll also apply this approach to VideoThumbsMaker, since I have seen in the past some mplayer.exe process left behind in Windows task manager...

**Comment by lfcnassif** [comment]
> @tc-wleite I'll also apply this approach to VideoThumbsMaker, since I have seen in the past some mplayer.exe process left behind in Windows task manager...

@tc-wleite please double check this commit f15b166 to be sure I didn't mess the logic (I used a wrong reference).

**Comment by lfcnassif** [comment]
PS: I thought the .join() call might block if mplayer is blocked and not killed properly, so I put it into an else block.

**Comment by tc-wleite** [comment]
> @tc-wleite I'll also apply this approach to VideoThumbsMaker, since I have seen in the past some mplayer.exe process left behind in Windows task manager...

Yes, it is not that common, but I have seen MPlayer processes left behind quite a few times.
It is great that you find a workaround!

**Comment by tc-wleite** [comment]
> @tc-wleite please double check this commit [f15b166](https://github.com/sepinf-inc/IPED/commit/f15b166b7b4a53b175f6a02ff3203df8afd9a0df) to be sure I didn't mess the logic (I used a wrong reference).

Sure! I will take a look tomorrow morning.

**Comment by tc-wleite** [comment]
> > @tc-wleite I'll also apply this approach to VideoThumbsMaker, since I have seen in the past some mplayer.exe processes left behind in Windows task manager...
> 
> @tc-wleite please double check this commit [f15b166](https://github.com/sepinf-inc/IPED/commit/f15b166b7b4a53b175f6a02ff3203df8afd9a0df) to be sure I didn't mess the logic (I used a wrong reference).

Changes look good to me! I ran a quick test successfully.

**Comment by lfcnassif** [comment]
> Changes look good to me! I ran a quick test successfully.

Thanks for testing!
