### ISSUE TITLE
Show Windows 10 Mail attachments in new references tab

### ISSUE THREAD

**Issue by FelipeFcosta** [sepinf-inc/IPED#1570]
I thought I had added this before, but it is not linking

13fa492 fixes it

**Comment by lfcnassif** [comment]
Hi @FelipeFcosta, something wasn't working without this? I think attachments already were being copied to reports.

**Comment by FelipeFcosta** [comment]
Yes, it was not showing the attachments (****.dat) in the new 'referencing' tab

**Comment by lfcnassif** [comment]
Ok since the new tab wasn't released yet, I'll change this to enhancement.

**Comment by lfcnassif** [comment]
This opens another point of discussion:

Currently we generate new empty subitems just to point to attachments that are other items in the case. Those files are renamed in FS so we put the correct names in the new subitems. But with the new Referencing tab, that didn't exist before, creating those subitems may not be so useful anymore, duplicates some results and we could stop creating them. Original attachment names are already printed (linked and clickable) in the email body. Just the relationship with the file in FS wouldn't be 100% clear.

One drawback is that the behavior would be a bit different than other email parsers, because they show attachments in the Attach/Subitems, while this parser would display them just in the References items tab, if we stop creating subitems for attachs. Currently attachments would be shown on both tabs, what can be confusing, not sure...

Should we change the parser behavior? What other devs think?

**Comment by lfcnassif** [comment]
And what about other email parsers? We could also list email attachments in the new References tab, but they are already listed in Subitems tab, not sure if this is desired for them (and for Win10 mail parser...).

**Comment by FelipeFcosta** [comment]
>- show email attachments as subitems for some mail formats (dbx, mbox, eml, emlx, msg, pst, ost) and for other formats (Win10 and *.partial.emlx for now) show as items in the new ReferencesTab, picking the more convenient approach for each format (may confuse users looking for attachments, they could be in 2 different tabs)

In this case, then the "attachs/subitems" should be renamed to just "subitems" to reduce confusion, since attachments can be found in 2 different tabs.

ps: for the MacOS *.partial.emlx mails, empty subitems are not being created for now, since the original name is not changed, so they're just listed in the referencing tab

**Comment by lfcnassif** [comment]
> In this case, then the "attachs/subitems" tab should be renamed to just "subitems" to reduce confusion, since attachments can be found in 2 different tabs.

Agreed.

> ps: for the MacOS *.partial.emlx mails, empty subitems are not being created for now, since the original name is not changed, so they're just listed in the referencing tab

OK. I'm waiting until we come to a conclusion, so we can review and merge PR #1562.

**Comment by lfcnassif** [comment]
And also PR #1571.

**Comment by lfcnassif** [comment]
> * show email attachments as subitems for some mail formats (dbx, mbox, eml, emlx, msg, pst, ost) and for other formats (Win10 and *.partial.emlx for now) show as items in the new ReferencesTab, picking the more convenient approach for each format

I no one objects, I plan to go with this approach.

**Comment by patrickdalla** [comment]
In my opinion attachments as subitems should be for embedded attachments.
Couldn't linked attachments as subitems cause some misinformations like
duplicate timestamp counting?


Em qui., 23 de mar. de 2023 20:04, Luis Filipe Nassif <
***@***.***> escreveu:

**Comment by lfcnassif** [comment]
> Couldn't linked attachments as subitems cause some misinformations like duplicate timestamp counting?

Possibly, but today, at least with Win10MailParser, timestamps are not copied to the created subitems that point to FS files. Anyway, those subitems will be removed with the new approach.
