### ISSUE TITLE
Fix typo in "HashDBLooupConfig.txt" file name

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#1696]
A user noticed that there is a typo in "lookup" in this configuration file name.
I noticed that a while ago, but forgot to open an issue or fix it.

Not sure if this should be classified as a "bug".

**Comment by lfcnassif** [comment]
Well, the feature is working properly, so it's not a bug to me.

Someone warned me about this too. My concern here is keeping compatibility with user custom profiles...

**Comment by lfcnassif** [comment]
Because HashDBLookupConfig.getTaskConfigFileName() can return just a single config file name, keeping compatibility with the old file would require undesired changes in the config loading api. Thinking again, keeping compatibility with the old file is not that important, users can just update their profiles. Keeping compatibility with 4.x cases in multicases is much more important, for example.
