### ISSUE TITLE
Itens are not being exported to the local disk when the MinIO task is enabled

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1701]
When the MinIO task is enabled and the enableAutomaticExportFiles is also enabled, files are not being exported to the output folder.

**Comment by lfcnassif** [comment]
Thank you @hauck-jvsh. This behavior was intentional a long ago (export to portable case or MinIO). I thought the behavior was changed at some point, seems it wasn't, my fault, sorry...

Ideally, I think the files shouldn't be exported to the portable case if MinIOTask is enabled and if `MinIOConfig.txt->updateRefsToMinIO` is true, exporting files locally and keeping no references to them makes no sense to me. But since this is critical to our current workflow, I'll apply the change and we can improve later.
