### ISSUE TITLE
Infinite loop in IOUtil.ignoreInputStream() causing thread leak and wasting CPU

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1757]
This method is creating a thread to read and ignore all values of an input stream, but it is closing when an error is throw and this may lead to infinity loop. This happens in the transcription cluster, for some reason the wave transcription fails, the process is closed and the thread never ends and uses 100% of a CPU. A thread dump of when the situation happened is attached.
[dump1.txt](https://github.com/sepinf-inc/IPED/files/11972779/dump1.txt)

**Comment by lfcnassif** [comment]
Great catch! But I'm not 100% sure if always exiting the read loop is the better solution. I think that method is used in other places and the original idea was to consume all InputStream content, even if exceptions are thrown. Maybe the Exception could be a random one (InterruptedIOException, RuntimeException)? I wonder what was the actual Exception thrown (EOFException, ClosedChannelException?) because if the external process was killed, the stream should end or be closed. Can you put an e.printStackTrace() and try to reproduce so we can better understand the exception and exit the loop just for some exceptions?

**Comment by hauck-jvsh** [comment]
I can change it to print the stack, but I'm not sure if it will be easy to reproduce, tomorrow I will try.

**Comment by hauck-jvsh** [comment]
The documentation of inputstream class says: 
Throws:
    [IOException](https://docs.oracle.com/javase/8/docs/api/java/io/IOException.html) - If the first byte cannot be read for any reason other than the end of the file, if the input stream has been closed, or if some other I/O error occurs.
    [NullPointerException](https://docs.oracle.com/javase/8/docs/api/java/lang/NullPointerException.html) - if b is null.

**Comment by lfcnassif** [comment]
Comment above may apply or not depending on the specific InputStream implementation. I don't remember all places calling this method but for those passing a stream coming from Process.getInputStream() or Process.getErrorStream(), maybe we can replace those calls for a new method which parameter is the Process object, so we can get the stream into the method and ignore it using the proposed fix?

**Comment by hauck-jvsh** [comment]
That is a good idea, but for this method I think if we can detect that the exception is stream closed we should abort this method too.

**Comment by lfcnassif** [comment]
Sure! Probably it was an IOException with "stream closed" message (unfortunately java has no ClosedStreamException), we can confirm it in a separate program, kill an external process and see what the exception is, so we exit in this situation.

Or maybe I'm thinking about crazy scenarios and we should always exit the loop. I don't even remember if that method is used for streams different than process streams. If not, I think we can exit.
