### ISSUE TITLE
Fix small inconsistencies in localization properties files

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1872]
While working in another issue, I noticed small differences between properties files used for different languages/locales.
There are a few missing entries, entries with typos in their key and duplicated entries.

Most are trivial to fix, so I will submit a PR.
I am not sure about the properties starting with the following prefixes:
```
Case.BusinessId
Case.PersonId
```

There are entries present only in "pt_BR", and some only defined for other locales.
I couldn't find any reference to them in the project, so I am not sure if they are actually being used.
Does anyone know if they can be removed?
Or which properties are (will be) used?

**Comment by lfcnassif** [comment]
Thanks @tc-wleite for catching this! About properties starting with
```
Case.BusinessId
Case.PersonId
```

I think they used to belong to an old case creation UI implemented by @filipesimoes that was never released because it was a bit coupled to a specific use case (in my personal opinion) and didn't have some important requirements. Since that UI code was never used, I removed it in version 4 and probably missed those localization properties and left them behind, sorry.

If they have no reference in code, I think it is safe to remove them.

**Comment by tc-wleite** [comment]
Thanks @lfcnassif!
I will double check, and remove those unused properties I mentioned in the PR.
