### ISSUE TITLE
Use group name as "Communication:To" in chat messages, instead of including each member

### ISSUE THREAD

**Issue by wladimirleite** [sepinf-inc/IPED#2011]
As discussed in this https://github.com/sepinf-inc/IPED/pull/1999#issuecomment-1839261218, Telegram groups with a lot of members can take too long to be processed and generate a very large case, if each member is included in the multivalued "Communication:To" metadata.

**Comment by aberenguel** [comment]
I processed an UFDR with 56GB.
It resulted in a case with 160 GB in `index` folder and 456 GB in `neo4j` folder.
I disabled `extractMessages` in `ParserConfig.xml` as workaround. Also disabled `enableGraphGeneration`. Now the case 6.8 GB in `index` folder.

I think that makes sense messages to be linked with the group, not the members of the group, since it is common  huge groups in Telegram (with thousands messages and thousands members). Maybe there should be a metadata in the group containing all members.

**Comment by lfcnassif** [comment]
Thanks @aberenguel for your feedback. This change will be definitely implemented and included in 4.2.0 version.

**Comment by aberenguel** [comment]
The fixes above resolved the problem. I've reprocessed the case with default profile and `phoneParsersToUse = all`.

|   | before fixes | after fixes |
| :---: | :---: | :---: |
| **index folder**  | 160 GB  | 8.7 GB  |
| **neo4j folder**  | 612 GB  | 0.7 GB  |
| **processing time**  | 16h ¹  | 1h 3min  |

¹ *canceled in "Generating graph database" due to huge time.*

**Comment by lfcnassif** [comment]
Thank you very much @aberenguel for testing!

**Comment by lfcnassif** [comment]
A small test with 12 WhatsApp databases also benefit from this:

|  | before fixes | after fixes
| :---: | :---: | :---: |
| index folder | 3 GB | 2.34 GB
| neo4j folder | 15 GB | 0.3 GB
| processing time | 43min | 17min

Graph rendering is also much faster.
