### ISSUE TITLE
Update libreoffice viewer to work with java 11

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#205]
It's not working, no error is shown in gui log...

**Comment by fsicoli** [comment]
The libreOfficer module should also be upgraded in order to be able to view Photoshop 32bit PSD files. LibreOffice 6.1 which currently comes with IPED doesn't support those files, but the newest one, LibreOffice 7.0.1 does.

**Comment by lfcnassif** [comment]
It is a different issue. Are your 32bit PSD files rendered in gallery? Possibly sending them to ImageViewer instead of LibreOfficeViewer could work, that solved a similar issue for a colleague of us and I thought about changing that config.

**Comment by fsicoli** [comment]
Some of them are rendered correctly in the gallery and some are not. And they all can be viewed externally using IrfanView, for instance.

**Comment by lfcnassif** [comment]
And have you tested opening those files using LibreOffice-7.0.1?

**Comment by fsicoli** [comment]
Yes, I did. Most of them worked using LibreOffice 7.0.1, but not all of them. 

I was looking for an open-source alternative to do that inside IPED, but I haven't found one yet.

**Comment by lfcnassif** [comment]
Maybe latest version of ImageMagick?

**Comment by fsicoli** [comment]
I was able to successfully convert those PSD files using the latest version of ImageMagick (ImageMagick-7.0.10-31-portable-Q8-x64). 

I used the command: 
convert "fileName.psd[0]" "fileName.jpg"

**Comment by fsicoli** [comment]
But they were also successfully converted with imagemagick's version that comes with IPED, by using the command:

magick convert -density 96 -sample 1280x1024 fileName.psd[0]" "fileName.jpg"

**Comment by lfcnassif** [comment]
Just to conclude this unrelated conversation (this ticket is about updating the java-libreoffice bridge to work with java14), changing PSD files to be handled by ImageViewer and increasing image thumb timeout should fix the PSD related issues.

@fsicoli opened #263

**Comment by tc-wleite** [comment]
This was tricky, but I think I found what is going on (and a possible solution).

I tried to add several tracing messages, made many attempts to invalidate, repaint, layout etc., but what finally helped was to create a standalone application to use the LibreOfficeViewer. Surprisingly, it worked fine with Java 11...
My next step was to create a new JFrame inside IPED application, and add the "noaPanel" from the LibreOfficeViewer to this frame, instead of the viewer's panel. And it also worked.

So the issue seems to be related to how a docking-frames container (dockable) deals with heavyweight (native) components (which is the case of the window LibreOfficeViewer). 
Mixing lightweight (Swing) and heavyweight (AWT / native) components is usually a bad idea, but sometimes we do need to use heavyweight components (like the LibreOffice native window).

After narrowing down the issue, I found in an old docking-frames forum (~2010) a workaround. 
Testing with version 1.1.2 (released years after that comment), it seems they improved (fixed?) how heavyweight components are rendered. 
So upgrading docking-frames to 1.1.2. fixes the LibreOfficeViewer issue (at least in my environment). It is working both with Java 8 and Java 11.

I also upgraded the JARs used by LibreOffice, which are simpler now (just 2 JARs), because I found some reports of issues with JDK versions >= 9, although they don't seem to be directly related to this particular issue.

I ran a large test with several different formats that IPED uses LibreOffice viewer, plus other file types (like images, PDFs, HTML, e-mails). 
LibreOffice viewer worked fine with both versions of Java, and I couldn't find any issue related to docking-frames (viewers worked fine and playing with the frames also worked as expected).

@lfcnassif, please, give a try in your environment when you got some time, as this issue may depend on the JVM used.

I will make a PR with the changes (basically on pom.xml files), but there is one important thing missing!
As I mentioned in https://github.com/sepinf-inc/IPED/issues/823#issuecomment-963691979 (item 12), docking-frames is not updated in the maven repository. 
I use a local repository as a workaround to test here, but **you will need to upload 1.1.2 version to IPED's repository**.

**Comment by lfcnassif** [comment]
Great! Thank you @tc-wleite! Upgrading docking-frames to 1.1.2 worked fine here with Liberica OpenJDK 11.0.13, Liberica 1.8.0_302 and the old embedded Oracle 1.8.0_152.

Will upload docking-frames 1.1.2 to iped repo and test the changes on Linux before merging.

**Comment by lfcnassif** [comment]
closed by #829

**Comment by lfcnassif** [comment]
Thank you @tc-wleite for debugging this, should have taken from you some time.
