### ISSUE TITLE
Failing to process Cellebrite XML Reports

### ISSUE THREAD

**Issue by fmpfeifer** [sepinf-inc/IPED#2089]
I'm trying to process a XML Report from Cellebrite Physical Analyzer (XML, not UFDR) with IPED 4.1.5, and IPED finishes without error, but the resulting case has much less data than what was on the original report. The same case, with an UFDR report, results in a huge case.

I investigated the issue, and will send a PR with a proposed fix soon.

**Comment by lfcnassif** [comment]
Actually this was an intentional change, made together with the change explained here:
https://github.com/sepinf-inc/IPED/discussions/1272

So I wouldn't classify it as bug. In the previous behavior, if user manually puts some files into the xml report folder, those files would be completely ignored. Is that fine? The idea was: if users points to the specific xml file, he really wants to process the xml report.

We may re-discuss what is the expected behavior.
