### ISSUE TITLE
Right click on table regression in 3.18 and 3.18.1 on Linux

### ISSUE THREAD

**Issue by reacan** [sepinf-inc/IPED#211]
Hello everyone!

I recently built IPED 3.18.1 using java-1.8.0_261-oraclejdk-amd64. Unfortunately when I try to right click items in the main view it does not bring up the dialog box, instead I have to go all the way up to the options button to perform different activities. 
Before that I was using bellsoft-java8-full-amd64 and I had the same problem + I could not create indexed reports (although this issue might be isolated to a specific case, not sure).

Which Java8 version would you recommend to be used with IPED?

P.S. running on Linux.

Regards,
Dāvis

**Comment by lfcnassif** [comment]
Hi @reacan,

Could you check if some error was printed in IPEDSearchApp.log in case folder? I recommend latest Oracle java 8, maybe it is a Linux related issue, will take a look.

About indexed reports, there is an issue with v3.18.1, already fixed in master, see #209. I will publish a new release because of that when I return from vacation, maybe before.

**Comment by lfcnassif** [comment]
Thanks for reporting. Fixed in master, snapshot in https://github.com/sepinf-inc/IPED/actions/runs/189323277

**Comment by reacan** [comment]
Thank you for the insight. Will check out the log and report back!
