### ISSUE TITLE
Support new version of WhatsApp Android database (no "raw_string_jid" column in "chart_view" view)

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#2326]
Today a police from MG state reported a WhatsApp parsing error caused by the absence of raw_string_jid column. He updated the application on the device to the latest version before extracting the database. Another more technical user from SP police reported the database schema changed. Seems we need to support a new database schema...

**Comment by wladimirleite** [comment]
This is somewhat critical. I can take a look ok this, unless someone is already investigating, at least to check if the changes were minor or it is a completely new schema.

**Comment by lfcnassif** [comment]
Thank you @wladimirleite! I just got 1 sample from the user, I still didn't take a look, I can share it with you tomorrow.

**Comment by wladimirleite** [comment]
It turned out to be something simple.
We were using a view ("chat_view") instead of reading "chat" and "jid" tables directly.
The view was changed (there is no "raw_string_jid" column now), but not the tables themselves.
In general, I think it is better to avoid using views when possible.
I am testing with more samples, but the fix is very simple, it should work fine both with old and new databases.
