### ISSUE TITLE
New command line option to allow filtering input folders by regex for triage scenarios

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#255]
I observed some "triage" profile processing taking time while recursing into system folders (with low cpu usage), although the files inside those folders would be ignored later by other module with specific rules of "triage" profile. Early stopping that recursion in specified folders would make "triage" profile faster. We have discussed that before in theory, right @fsicoli?

**Comment by lfcnassif** [comment]
@fsicoli could we get rid of scripts with exclude rules with this?

**Comment by fsicoli** [comment]
Early stopping that recursion on a folder level would be a great option to improve processing. Currently, the rules are on a file by file basis, so every file within that folder is tested to see wether or not it should be filtered-out. 

On the other hand, having those "black-listed" folders passed on to IPED through command-line would require the user to explicitly pass those parameters to IPED every time he wanted to use that feature. So, in addition to passing them on to IPED via command-line, I suggest also being able to input those "excludePatterns" by means of a configuration file or even profile file variables, so that it's easier to the user to run in a pre-defined way.

**Comment by lfcnassif** [comment]
I think about new users of the tool using "triage" profile and it automatically ignoring whole directory trees, that's why I proposed an explicity option for that. And we can include these command line parameters in our triage Linux distro by default.

**Comment by lfcnassif** [comment]
@tc-wleite @fmpfeifer any thoughts on this?

**Comment by tc-wleite** [comment]
Well, I don't have much experience using triage profile myself, but I personally would prefer to use a configuration file in this case.
Probably the user will setup ignored folders once and will make small changes depending on the case. 
And as it can be a long list, the user will want to create a batch/script file anyway, instead of typing every time.
 
Regarding your concern @lfcnassif, maybe the default configuration could have a suggested list of ignored folders in a comment and nothing in the actual configuration. And in the Linux distro you mentioned, the default ignore list would be enabled.

**Comment by fsicoli** [comment]
I agree with Wladimir. Currently, the list has over 70 black-listed folders. It has become a little too long to pass all that via command-line.

**Comment by lfcnassif** [comment]
ok I replaced the cmd line params by a new option in AdvancedConfig.txt of triage profiles only. That is disabled by default and doesn't have a default commented value, but users can configure it.

I didn't remove the old scripts, because they work with all datasource types. The new option works just when processing mounted folders.
