### ISSUE TITLE
Caused by: IndexWriter is closed

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#302]
Just got:
[ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
java.lang.Exception: Worker-0 Error while processing ...
...
Caused by: org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
...
Caused by: org.apache.lucene.index.CorruptIndexException: checksum failed (hardware problem?)
...
ERROR!!!
Check the log at ..

**Comment by lfcnassif** [comment]
Seems your index became corrupted. Could you attach the full log?

**Comment by MariasStory** [comment]
Hi @lfcnassif, thanks for the answer.
Indeed, it seems that the index got corrupted.
I repeated indexing and it worked.
Just to mention, I had such problem before.

It would be nice to make sure that the tool is reliable.
Even if there is such error, maybe the processing can be re-done, in order to make sure that the tool just works.

**Comment by lfcnassif** [comment]
The approach was always to abort when unexpected errors are found, instead of just logging and continuing and hiding possible dangerous problems from the user.

There is the --continue option to resume an aborted processing e.g. in case of abrupt power off, temp disk full, antivirus blocking the tool with false positives, some kinds of OutOfMemory issues. But I don't recommend using it if your index is corrupted.

Without the asked full processing log and with just the above info, one can conclude maybe your hardware is not reliable...

**Comment by lfcnassif** [comment]
Probably user hardware problem.
