### ISSUE TITLE
Feature Ignore Duplicates

### ISSUE THREAD

**Issue by GRCWill** [sepinf-inc/IPED#574]
The "ignore duplicates" feature is a great functionality for several reasons (in my case it is considerably reducing the size of the case and I believe that consequently the search speed, loading of the case etc).

However, there are files that are not visible at the time of review, for example, if a file attached to an email is found in two different messages, it will be available on the "Attachs \ Subitems" tab for the first message only. The second message will have an indication of the attachment in the header, however the "Attachs \ Subitems" tab will be empty, since the attachment was ignored by de-duplication.

Is there any way to not lose the reference to the ignored file? This creates some difficulty for people who are reviewing the data because at certain times it is necessary to take a look at the attachment of a message but it does not appear in the "Attachs \ Subitems".

Note: This was observed only in cases of OST and PST files. In messages in EML format, the reference is also lost in the "Attachs \ Subitems", but in the header there is a "link" where it is possible to open the file in the external viewer.

**Comment by lfcnassif** [comment]
Ignoring duplicates (same hash) for sure reduces the number of items in the case, helping sorting, but this can be achieved using the duplicate filter. And, generally, I think it doesn't have a huge impact in processing or search time or case size in disk. IPED by default reuses the results of CPU intensive tasks, like OCR, video thumbs extraction and others, over duplicated files. Duplicate subitems extracted from containers also doesn't use additional space in case folder. And I think index size also doesn't increase that much if you index duplicates, because the same content is indexed.

Actually I think this feature is dangerous, and I have already considered removing it, exactly because the issue you described, you may miss duplicate files located in more important paths, or with different MAC times. But I kept it so far...

**Comment by lfcnassif** [comment]
So I wonder to know what other devs think about this feature: if it could be removed like I have already considered, or if it could be improved some way to keep the reference to ignored files like you suggested.

**Comment by GRCWill** [comment]
Got it, thank you very much for the answer.

Would merging some metadata fields be a possibility? At least the path field.

I have a case of 5 million items, with the option "ignore duplicates" enabled. I will try to process the same dataset without "ignore duplicates" to make some comparisons.

**Comment by lfcnassif** [comment]
> Would merging some metadata fields be a possibility? At least the path field.

Well, this is not an easy implementation with current processing pipeline design. And ignored attachments will continue to be missed in subitems tab, it uses id<->parentId relationships, not paths, because you can have several emails with same paths and subjects but different content and attachments.

> I have a case of 5 million items, with the option "ignore duplicates" enabled. I will try to process the same dataset without "ignore duplicates" to make some comparisons.

This would be an interesting evaluation.

**Comment by lfcnassif** [comment]
As discussed here and on #931, this feature is inherently dangerous and with very hard issues to workaround. Instead of removing the feature, a big WARNING in config file was added. For now, no efforts will be done to try to improve it, at least from my side, I think there is no easy reasonable solution.
