### ISSUE TITLE
Deadlock if (100k+numThreads) sqlites are found

### ISSUE THREAD

**Issue by gaffinet** [sepinf-inc/IPED#576]
Hi

I have a hard-drive with a EXT4 filesystem.
The process of ingestion starts fine, but after some time, the process (all the threads) is block in SignatureTask
I also have tried to abort the process and restart with --continue. The result is the same.

![image](https://user-images.githubusercontent.com/9380336/120155386-0def5580-c1f1-11eb-936a-c3c751b3dda9.png)

![image](https://user-images.githubusercontent.com/9380336/120155726-6fafbf80-c1f1-11eb-82b2-5373fe2051ee.png)

The screenshots suggest that the problem refers to the same file. The name of the folder are quiet start, even with emojis but then names cannot be disclosed here.

Thanks for your help

**Comment by reacan** [comment]
I had a similar issue once. I solved it by mounting the image read/write and deleting the problematic files. If you take this route be sure to create a backup of the original image and to check the problematic files manually :)

**Comment by gaffinet** [comment]
> I had a similar issue once. I solved it by mounting the image read/write and deleting the problematic files. If you take this route be sure to create a backup of the original image and to check the problematic files manually :)

Hi
currently, I'm creating a logical copy of all the files. Perhaps, the ingestion on the logical files works better.
The problem with deleting the problematic files, is that I don't know how many files will cause these problems and I don't want to repeat this process multiple times.

**Comment by lfcnassif** [comment]
Could you send a thread dump of the process? jstack -l pid

**Comment by lfcnassif** [comment]
Not sure if this is related to SignatureTask or FileSystem reading, the thread dump will help.

**Comment by lfcnassif** [comment]
If it is related to FileSystem reading, enabling "robustImageReading" in AdvancedConfig.txt should help because it has timeout control when reading files. The thread dump would show if it is the case or not, and help identify the issue if it is related to signature check itself.

**Comment by lfcnassif** [comment]
The thread dump recommendation is explained at https://github.com/sepinf-inc/IPED/wiki/Troubleshooting#processing-frozen

**Comment by gaffinet** [comment]
robustImageReading is enable

Hi dumped the stack of the java process which uses the most memory:
[jstack_dump.log](https://github.com/sepinf-inc/IPED/files/6571650/jstack_dump.log)

**Comment by lfcnassif** [comment]
Thank you @gaffinet for the thread dump!

I think this is a rare situation related to your huge case. SQLite files (and a few uncommon types) are sent to a second processing queue. But queues are limited to 100K items to not use too much heap memory. When the max queue size is hit, the thread trying to add items to it (normally the item producer thread) sleeps some time until queue size decreases. But seems worker threads are sleeping because the second processing queue is full of 100k items (I guess most are sqlite files given the .db extension and because other types processed in second queue are very uncommon).

I pushed a not ideal workaround to not limit the second processing queue size, as this queue normally handles specific file types and should not grow crazily, please test if this snapshot solves the issue (you could use it with --continue):

https://github.com/sepinf-inc/IPED/actions/runs/894293070

If other dev has a better solution, please let me know.

**Comment by gaffinet** [comment]
@lfcnassif thank you for the quick fix.
It seams to work now, but I have to wait till the ingestion is finished (will take some days)
Also, I didn't notice any problems with the memory consumption for now, but I will continue to monitor this.

**Comment by lfcnassif** [comment]
As soon as the processing of this evidence is finished ok (or not), please let me know, so I will apply the fix to master branch.

**Comment by hauck-jvsh** [comment]
I don't see an easy solution, as the second queue must wait the first one ends to start. Maybe a review to reduce the number of files sent to the second queue, but even this cannot guarantee that the process will finish. One solution is to save the queue in a temp folder if it grows further than a threshold, but this may add an extra complexity and may have a performance impact.

**Comment by lfcnassif** [comment]
Thanks @hauck-jvsh. Currently sqlite files are processed later to be processed together with wal logs found. I also thought about using some kind of in disk queue, but items are not serializable today and this is a sensible change.

After #24 is implemented, in the future I plan to add all items to index in fastmode and simultaneously read them from index to run the normal pipeline. So, after the evidence is decoded, all items should be in index and could be queried, so second queue could be processed before first queue ends, or could be merged with it...

Other alternative is querying items directly from sleuthkit DB instead of from index, but that would not work for cases where sleuthkit isn't used (mounted folders, ad1, ufdr, udf iso...)

**Comment by gaffinet** [comment]
> As soon as the processing of this evidence is finished ok (or not), please let me know, so I will apply the fix to master branch.

Hi. 
I have 2 images, the first one I restarted completely and the second one I used --continue. Both ingestions finished without further problems.

I didn't notice any problems with the memory consumption, but I also have a VM with 64GB RAM and 16 cores. I ran two iped instances in parallel (one for each image). The first image has about 105k sqlite files and the second image about 230k sqlite files.

**Comment by lfcnassif** [comment]
Thanks @gaffinet. Good to know my diagnostic was correct. Each item uses about 1-2KB of heap, so even very exceptional cases like this with hundreds of thousands of sqlites would use some hundreds of MB for the processing queues.

Thanks for reporting and for the thread dump again.

**Comment by lfcnassif** [comment]
fixed by dd2a95863ed64d36e120c5aacef02fc30ddfbc34
