### ISSUE TITLE
Store all email headers as metadata

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#65]
Currently just subject, date, from, to, cc and bcc are stored. It would be useful to index all header fields as individual metadata, so user could filter or sort by those fields. EML, PST and OST parsers should be updated.

**Comment by thalespr** [comment]
If it's not in a priority queue, I think I can do that.

**Comment by lfcnassif** [comment]
It is not, feel free to take it, thank you.

**Comment by thalespr** [comment]
Started working on it. The code for PST emails is already done, but a question came to my mind: do you want really all the e-mail headers to be added as metadata or just some more important headers that aren't currently on it? There are headers that might not be relevant or even provide redundant info that are stored in other fields. At the first moment, I just included the headers that are more important in my opinion (like the Message-ID...), but the code is flexible enough to include all the other headers without some significant effort... So let me know your opinion on this in order to make the needed adjustments on the code. Thanks in advance.

**Comment by lfcnassif** [comment]
Maybe we could use a black list approach? Excluding unimportant or duplicate headers instead of choosing some specific ones? Servers could add custom headers and they could be important. So we wouldn't loose possibly important info?

**Comment by lfcnassif** [comment]
Closed by #456
