### ISSUE TITLE
Shareaza parser missing some files

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#698]
Files, that are present in Shareaza albums but are not in the filesystem, aren't showed in the HTML output. This was found by  Hugo Kling a college from São Paulo.

**Comment by fmpfeifer** [comment]
It turns out that shareaza stores two sets of files in Library{1,2}.dat:
- Library Folders and Files: Files stored in the same layout as in the user's filesystem
- Album Folders and Files: Files sorted in classes (albums).

The parser reads and decodes all of those, but is not exporting the album files to the output table.
