### ISSUE TITLE
maxConcurrentRequests doubt

### ISSUE THREAD

**Issue by rafael844** [sepinf-inc/IPED#751]
errorCode=TooManyRequests details=The number of parallel requests exceeded the number of allowed concurrent transcriptions.

When I get the error above, the audio go back to the queue or it skips the trancription?

**Comment by lfcnassif** [comment]
Currently it is retried up to 3 times in Microsoft implementation because of spurious errors, Google impl just tries once. But the last time I tested Google service it was always throwing this error much much before the quota limit was reached:
https://github.com/googleapis/java-speech/issues/171

I still need to test their non beta library, but I think it is some issue with their Brazilian end point.

**Comment by rafael844** [comment]
Im using Microsoft Azure, with maxConcurrentRequests  se to 4. I dont know our number of allowed concurrent transcriptions because its a test with Microsoft, If we are  exceeding it I'll let you know. Thank you.

**Comment by lfcnassif** [comment]
If you aren't using a credit card, your limit is 1. If you are using, looks like MS increased it from 20 to 100:
https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/

**Comment by rafael844** [comment]
You were right. We were using the free version, now we are with a paid one and Its wirking properly.
Thank you.
