### ISSUE TITLE
Extract frames from Animated GIFs and APNGs

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#763]
Currently there is no special treatment for animated GIFs, they are just displayed as static images, showing their first frame.
Although this is not that common, important child sexual abuse material using this file format was identified here in an recent case.

I see a few options: 

1. Treat such files as videos (so part of their frames will be extracted and displayed as their visualization).
2. Extract all contained images (frames) as subitens.
3. Change the image viewer to animate their visualization.

Adding such files to a specific category would also be useful (maybe "Animated Images", as a subcategory of videos).
There are also similar image formats that support animated sequence of images (e.g. APNG, WebP and AVIF).

@lfcnassif, any thoughts? 
Has anyone brought this up before?

**Comment by lfcnassif** [comment]
No one, but a long time ago I noticed this, I didn't create a ticket and then I forgot...

If mplayer supports those file types, I think option 1 will be the simpler solution and would be enough. Option 2 would allow running OCR on each frame, but I think it wouldn't help CSAM cases. And I think option 3 **alone** isn't good, because the embedded frames won't be displayed in the gallery.

**Comment by tc-wleite** [comment]
> If mplayer supports those file types, I think option 1 will be the simpler solution and would be enough. Option 2 would allow running OCR on each frame, but I think it wouldn't help CSAM cases. And I think option 3 **alone** isn't good, because the embedded frames won't be displayed in the gallery.

I made a quick test and MPlayer does to support such files.
APNG files (at least the few I got here so far) are also handled by MPlayer.

Unfortunately, it seems that there is no metadata already being extracted that indicates which images are animated, neither for GIFs nor for APNGs.
My idea is first to add such information (the number of frames, something like "AnimatedFrames", for images with more than one frame), then handle these files in VideoThumbsTask.

**Comment by tc-wleite** [comment]
A quick update: 

**AnimatedImageParser**
I tried to add a parser to extract the number of frames (AnimatedFrames), and then use this information in VideoThumbTask, but later I realized that ParserTask runs after VideoThumbTask.
So I added the code to check this information (for GIFs) and set it as metadata (if there are multiple frames) in the VideoThumbTask.
It is not my initial idea, but as there are other metadata being set inside VideoThumbTask, I don't think this will be a problem.

**MPlayer**
Although MPlayer supports animated GIFs and APNGs, the code we use to call it expect that videos have a duration property, which is not present for these files (at least MPlayer doesn't extract it). So it didn't work out of the box.
For fixing this and produce better results (evenly sampled frames), I had to make a few changes in VideoThumbsMaker class, so it has now some code to handle animated images (and to receive the number of frames present in the processed image.

**APNG**
Although using ImageIO reader.getNumImages() worked fine for GIFs, it always returns 1 from APNGs (probably it wasn't implemented properly in the decoder, as it is a rather unusual format).
I am testing a simple alternative solution. 
If it fails, I will leave the APNG's support as a future improvement.

**Comment by tc-wleite** [comment]
I changed the name of the property from "AnimatedFrames" to "AnimationFrames", which is the name used by ExifTool.
APNG is working, so I updated the issue description.
I will collect more samples to test before submitting the changes.

**Comment by lfcnassif** [comment]
> but later I realized that ParserTask runs after VideoThumbTask.

That was changed because of #100. I just thought about other possible approach to #100, maybe the text + metadata concatenation could be done by an utility method (and not by IndexerDefaultParser) and this new method could be called instead of getParsedText() by RegexTask, IndexTask and others... But the metadata of embedded files will no longer be indexed or shown in Text tab (e.g. images inside a doc have their metadata extracted and indexed, even without expanding the doc), not sure how to keep this behavior. If you think it is worthy, I can think more about this idea...

**Comment by lfcnassif** [comment]
Thanks @tc-wleite
