### ISSUE TITLE
Try to optimize image thumb generation

### ISSUE THREAD

**Issue by lfcnassif** [sepinf-inc/IPED#81]
ImageThumbTask starts a new imagemagick process to convert each image file not supported by java. Imagemagick has a server mode to listen and answer requests, but all images will need to be spooled to disk, because Stdin/stdout, currently used to send images, is used for communication in server mode. But, when indexTempOnSSD is on, images are already spooled to temp folder.

Also, some ImageUtil code (getThumb and getOrientation) seems to rely on catching exceptions when file is not jpeg, that is slow for the JVM.

**Comment by lfcnassif** [comment]
hey @tc-wleite , do you think the last comment above makes sense? Or inserting a test "is jpeg?" will not result in measureable speed up?

**Comment by tc-wleite** [comment]
My guess is that the gain will be small, but I think inserting a "is jpeg" is a reasonable change as there is no point in running a piece of code that will fail for sure, and avoiding that requires a simple change.

**Comment by lfcnassif** [comment]
@tc-wleite add a isJpeg check in 94e5130ca662835b8216c51d2f2694d0be0e7188, speed up was negligible.

About real optimization, I see a number of cases where image thumb creation takes a lot of time of overall processing. If we change imagemagick to server mode, maybe we can get good speed up sending all image types to imagemagick. C code should be faster than java when dealing with matrixes and maybe imagemagick uses hardware acceleration? The communication overhead could slowdown a bit...

**Comment by tc-wleite** [comment]
@lfcnassif, ImageMagick should be faster, but my guess is that it won't be too much faster as current Java's code already has many important optimizations (like reusing existing thumbnails and subsampling images). On the other hand, if a large number of images are sent to ImageMagick, using the server mode should provide a meaningful gain.
By the way, I don't remember seeing ImageThumbTask taking a lot of time too often. Did you investigate if some kinds of image (carved, invalid, an unusual type, high resolution etc.) are taking much more time than the others?
I remember we did some benchmarks many years ago. I can try to investigate it here in more detail. Maybe adding some detailed stats in the processing log would be a good idea.

**Comment by tc-wleite** [comment]
After running many tests (using Windows) and trying a lot of things, I only found minor improvements, but made a few hopefully useful observations:
- External calls to ImageMagick are slow (average time here was ~300 ms/image, including both valid and corrupted images).
- Many cell phones I tested had a lot of HEIC and some WEBP images. Both formats are NOT supported by internal Java parsers, so all these images were processed by IM.
- Other operations were significantly faster, so improving them would provide a minor gain.

**HEIC**
-	Currently, HEIC processing is extremely slow in IM (2~5 seconds/image). Other IM users reported this issue. Same images are processed ~5-10x faster by Windows decoder. JPEGs with same size/resolution are processed ~10x faster by IM.
-	Almost every HEIC image I inspected contains an embedded thumbnail (320x240 pixels). Unfortunately, IM (even the current latest version) can’t extract it (although it can extract - not only generate - these embedded thumbs for other formats, like JPEG).
-	I managed to extract these thumbnails using another library (libvips). It is much faster (~200 ms/image) as expected, but it uses native code, and may have cross platform and licensing issues, so I think it is not a good option.
-	Using the Nokia’s Java library (which also relies on native code), I managed to extract raw thumbnail data, but this library doesn’t decode image content (it only handles the HEIC container) and its license is very restrictive, so it can’t be used neither.
-	The ideal solution would be a pure Java library that extracts embedded thumbnails or decodes the full image (but faster than IM).
-	It is possible that IM implementation is improved in future versions, to extract an existing thumbnail from HEIC images or to speed up the full image decoding.

**WEBP**
-	IM’s decoding speed for WEBP images is similar to observed for JPEG images. So, it is not as critical as HEIC. 
-	Having a pure Java decoder would be a better (and faster) option though. Unfortunately, I couldn’t find any. The existing libraries rely on native code and didn’t work as expected in my tests (failed to decode most of the testing files, which were successfully processed by IM).

**IMAGE MAGICK**
-	External calls are slow. A server mode (that keeps an open process) would help, but I couldn’t find this option.
-	I found a library (JMagick) which is supposed to make JNI calls to IM (instead of using the command line tool). Unfortunately, it seems to be an abandoned project. 
-	I tried several parameters combinations when calling IM, for HEIC and other types of images, but couldn’t find any significant speed up. 
-	Limiting to a single thread (@lfcnassif‘s suggestion) did help, but the average speed up was between 0-5%. I committed this change (in GraphicsMagicConverter.java).
-	Using IM dynamic libraries (currently IPED is using static) helped a bit. Unfortunately, IM pre-built portable distributions use static libraries, so it is necessary to build it from source code.
-	Building IM with VS2019, using dynamic libraries, portable option, disabled OpenMP and 32-bits, provided an average gain between 0-20% in my tests. 
-	Reducing the number of files processed by IM would also help, but there are common formats images (JPEG, PNG) that were successfully processed by IM after failing in internal (pure Java) methods. Although these images were exceptions, I believe the current solution (sending all images that failed to IM) is still the best option.

**POSSIBLE (FUTURE) IMPROVEMENTS**
-	Use IM built from code, as mentioned before. It would need more tests using different Windows versions (I used Windows 10 64-bits), but it seems to make calls to IM slightly faster.
-	Check new IM releases, to see if HEIC thumbnail direct extraction is supported or if the full HEIC image decoding is improved.
-	Look for new pure Java libraries that handle HEIC and/or WEBP.

**PERFORMANCES STATS**	
-	I added detailed performance information to processing log. It prints, when the task is finished, the total number of calls and average elapsed time for the main image thumb generation steps, and for each file type.
-	It helped a lot understanding which were the critical steps and file types. The overhead of these measures is extremely small compared to actual thumb processing time, so I would recommend to keep this information in the log.

**Comment by lfcnassif** [comment]
Thank you very much @tc-wleite for all your tests and research! I defer to you any decision here. Agreed to keep detailed log stats.

About imagemagick server mode, I must be crazy or dreamed with it, couldn't find it too. Will search for it a bit more before giving up.

**Comment by lfcnassif** [comment]
Just to document here, @tc-wleite already tried this, other possible improvement for HEIC is try to extract the embedded thumb (hopefully with java code) and send just the thumb to imagemagick for decoding.

**Comment by lfcnassif** [comment]
Found the batch (not server) or interactive mode:
http://www.graphicsmagick.org/batch.html
https://github.com/sharneng/gm4java
http://kennethxu.blogspot.com/2012/10/integrate-java-and-graphicsmagick.html#GraphicsMagickIntegration-ProposedSolution

Unfortunatelly, seems just graphicsmagick has this option, and it does not support webp nor heic...

**Comment by lfcnassif** [comment]
hey @tc-wleite, while profiling with jvisualvm, I found the cpu spending a lot of time in FileCacheImageInputStream. I was surprised, although I have seen imageio temp files many times. Disabling it, resulted in 3x speed up in thumb creation in some tests with ufdr reports (and 20% less overall processing time). I did not detected thumb creation errors with this change. Maybe this effect is bigger in my machine because of my very old SSD, but that should help with HDDs too.

**Comment by tc-wleite** [comment]
@lfcnassif, that is an impressive speed up! 
You mean `ImageIO.setUseCache(false);`, right?
Looking at Java API documentation here, it makes sense to disable it, considering how IPED works... 
I will try to run some tests here.

**Comment by lfcnassif** [comment]
Yes. I thought the method name and docs a bit confusing, but just confirmed now ImageInputStream.isCachedMemory() is returning true.

**Comment by tc-wleite** [comment]
My initial test (1.05 million images, part of DIE's training set) just finished here. 
There was also a huge gain, not only in ImageThumbTask, but also in other tasks that use ImageIO:
```                                Cache 
                    Original  Disabled
                    Time (s)  Time (s)  Reduction
ImageThumbTask          2374       902        62%
DIETask                 1362       935        31%
ImageSimilarityTask      574        97        83%
```
I also didn't observe any problem, so it is definitely a great finding, @lfcnassif!

**Comment by lfcnassif** [comment]
I thought it could improve other modules, but not that big! Thank you for testing!
