### ISSUE TITLE
Some animated webp images are not being rendered

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#852]
I found that some animated webp images are not being rendered and thumbs are not generated for them. There are 10 examples attached. @tc-wleite, @lfcnassif  as you were working with gifs before do you have any clues? 
[webps.zip](https://github.com/sepinf-inc/IPED/files/7609583/webps.zip)

**Comment by tc-wleite** [comment]
WEBP are currently handled by the external conversion tool (ImageMagick). 
I can try to take a look here what is going.

**Comment by lfcnassif** [comment]
Thanks for the samples @hauck-jvsh. I just did a small test and imagemagick version embedded into IPED is not able to decode them. Latest imagemagick 7.1.0 is able to extract all frames from those webp images.

I also tested mplayer currently distributed with IPED and latest build by https://oss.netfarm.it/mplayer/, and none of them are able to decode those webp images. This would make things more difficult, because currently supported images with multiples frames (GIFs and aPNGs) are handled by mplayer today, not by imagemagick, as described at #763.

One simple very limited workaround would be just updating imagemagick version to extract at least the first frame of those animated webp images, as was done before for GIF/aPNG. Full support for animated webp could be implemented in another ticket, this possibly would need to change the current approach of handling multiple frame images, that can affect GIF/aPNG current results. Thoughts?

**Comment by hauck-jvsh** [comment]
For me, updating the imagemagick to decode the first frame will be a great advance, because with the current behavior the user may think that the image is corrupted. Extracting more frames like is done for gifs could be done later as you suggest.

**Comment by lfcnassif** [comment]
ok, I'll update imagemagick and create another ticket to support multiple frames webps and possibly other multiple frames formats not supported or handled in a different way (heif, tif, etc)
