### ISSUE TITLE
Error: Unable to initialize main class dpf.sp.gpinf.indexer.IndexFiles

### ISSUE THREAD

**Issue by Prosecut** [sepinf-inc/IPED#883]
Hello.

I just installed Iped. All was fine, however trying to start program, I got error:
Error: Unable to initialize main class dpf.sp.gpinf.indexer.IndexFiles
Caused by: java.lang.NoClassDefFoundError: dpf/sp/gpinf/indexer/util/IPEDException

![Capture](https://user-images.githubusercontent.com/96477788/146928331-2fd3b1f5-8e23-4cbb-8746-c977407c4e7b.PNG)

Cant figure it out how to fix it. I tried switch Java versions but useless.

**Comment by lfcnassif** [comment]
What iped version are you using? What was the command line used?

**Comment by Prosecut** [comment]
I am using iped-4.0.0-snapshot. Command line command: 
![Capture2](https://user-images.githubusercontent.com/96477788/146936382-1812672f-248e-40e5-9379-897a7c3fc927.PNG)

**Comment by lfcnassif** [comment]
Did you build from source? What command did you use to build and what was the output?
Or downloaded a snapshot from https://github.com/sepinf-inc/IPED/actions?

Some weeks ago snapshots were returning this error because of an invalid/empty META-INF/MANIFEST.MF file in iped.jar. But last snapshots are working fine, seems it was some temporary github CI issue.

**Comment by Prosecut** [comment]
Hello.

I ones more deleted all, install Liberica OpenJDK 11 Full JDK.
Used step by step:
git clone https://github.com/sepinf-inc/IPED.git
cd IPED
mvn clean install

Installation was smooth, however whant I try to use iped-4.0.0-snapshot\iped.exe it get same error: 
Error: Unable to initialize main class dpf.sp.gpinf.indexer.IndexFiles
Caused by: java.lang.NoClassDefFoundError: dpf/sp/gpinf/indexer/util/IPEDException

**Comment by Prosecut** [comment]
When I use iped-4.0.0-snapshot\iped.jar, nothing happens

**Comment by lfcnassif** [comment]
What version of maven are you using?

Could you unpack iped.jar (it's a zip file) and share the META-INF/MANIFEST.MF file?

**Comment by Prosecut** [comment]
Sure.

File content is such:

Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven 3.8.3
Built-By: Ekspertizes
Build-Jdk: 11.0.13
Main-Class: dpf.sp.gpinf.indexer.IndexFiles


Maven:
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: C:\apache-maven-3.8.3
Java version: 11.0.13, vendor: BellSoft, runtime: C:\Program Files\BellSoft\LibericaJDK-11-Full
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by lfcnassif** [comment]
Thanks! I was able to reproduce your issue with maven-3.8.3, seems a regression with that version, the maven-jar-plugin is not populating the Class-Path correctly in the MANIFEST.MF file. Try to upgrade to maven-3.8.4, that solve the issue here. Possibly this same issue was affecting the github CI builds weeks ago.

**Comment by Prosecut** [comment]
Thank you. 
Yes, the newest version of Maven solved it.
