### ISSUE TITLE
Save custom panels Layout

### ISSUE THREAD

**Issue by hgguido** [sepinf-inc/IPED#933]
Is there any way to configure the layout so that it stays persistent?
I mean the distribution of the panels and also the visible columns.
This is very customizable and this is great, but I have to tweak everything again every time.

**Comment by lfcnassif** [comment]
> Is there any way to configure the layout so that it stays persistent?

Currently not, although this was already proposed informally.

> and also the visible columns.

Doesn't this option work for you?

![image](https://user-images.githubusercontent.com/7276994/150375976-8b0e2d21-16af-4c60-929e-07ff6e95b9f1.png)

**Comment by hgguido** [comment]
Yes, i am currently using this option. But it is necessary to uncheck the option "manage columns automatically (slower)" every open otherwise the default that was saved is lost.

**Comment by hgguido** [comment]
That´s great. I will try this option next time.

Thank you very much!

**Comment by tc-wleite** [comment]
@lfcnassif, are you (or someone else) working on this?
If it is not the case, I would like to implement this, as some users here requested this feature.
Took a quick look, it should be straightforward...

**Comment by lfcnassif** [comment]
I'm not, thank you @tc-wleite!

**Comment by tc-wleite** [comment]
DockingFrames already has utility methods to save and restore the layout of panels, so it was straightforward to implement, as expected. These functions in the library has minor flaws (e.g. an externalized and maximized panel is restored just as an externalized panel, losing its maximized state/position), but so far I didn't find anything critical. 

There are also a few "extra" configurations ("outside" docking frames), like the number of columns in the gallery and the main windows position/state that should be saved/restored, which were also simple to implement.

Finally, as the saved layout (if present) is restored when the application is opened (same behavior of saved columns layout), a few minor issues arised (e.g. when the gallery or the map are the top panel when the application starts, instead of the main item table). 
I already solved most of them, and will (hopefully) take care of the rest in the next days, but I wanted to mention this here, as there will be some minor code changes that don't seem directly related to the original issue.

**Comment by lfcnassif** [comment]
I was aware docking frames has such support, but didn't know it was so straightforward. Thank you @tc-wleite for taking care about all the other details!
